### ISSUE TITLE
Deveria aceitar o pull request do jose Helio

### ISSUE THREAD

**Issue by Qwwerty** [vanessafc/vanessafc#4]
Lorem ipsum hendrerit proin nisi habitant phasellus lacinia, commodo id sem nisl venenatis maecenas erat, tincidunt euismod iaculis etiam lobortis nullam. convallis senectus enim pulvinar augue tempor neque blandit bibendum vestibulum, arcu semper ullamcorper cubilia nostra adipiscing in dictum, placerat ornare proin curae suscipit pretium orci odio. curabitur pharetra fermentum lacinia dapibus sagittis faucibus tristique leo, praesent at potenti leo ultricies dolor praesent sem viverra, suscipit egestas donec dictumst elementum morbi etiam. viverra imperdiet porta adipiscing eu potenti curabitur, cursus primis tempor sociosqu praesent eu egestas, netus donec sollicitudin augue aliquet.

**Comment by vanessafc** [comment]
Já foi aceito.
